services:
  navdesk:
    image: sstarbucks/navdesk:latest
    container_name: navdesk
    restart: always
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Shanghai
      GIN_MODE: release   # 生产模式 默认debug
    volumes:
      - ./data:/app/data
